export type ControlType =
    "!speed" 
    | "!volume" 
    | "!stop" 
    | "!loopmany"
    | "!loop" 
    | "!looptarget"
    | "!cut" 
    | "!combine" 
    | "!jump" 
    | "!target" 
    | "!flash" 
    | "!startpos" 
    | "_pause"
    | string